### ISSUE TITLE
Updating front-end

### ISSUE THREAD

**Issue by hbgit** [hbgit/Map2Check#8]
- [x] Review tool input options
- [x] Improve how the tool modes are executed
- [x] Review the counterexample generation

**Comment by RafaelSa94** [comment]
We should also use LLVM API in the Caller

**Comment by hbgit** [comment]
Thanks, could you describe or point an example? And could you point any part of the code? To apply that.

**Comment by RafaelSa94** [comment]
We should use the Clang/LLVM API instead of calling external binaries. For example, the older version used [this](https://github.com/hbgit/Map2Check/blob/381431838ea076d93df70cc0a3b86690c824f7bc/modules/frontend/caller.cpp#L112-L131)

Places where refactoring is needed:
- [ ] [Add NonDet pass](https://github.com/hbgit/Map2Check/blob/master/modules/frontend/caller.cpp#L83-L118)
- [ ] [Add Analysis pass](https://github.com/hbgit/Map2Check/blob/master/modules/frontend/caller.cpp#L120-L192)
- [ ] [Link Map2Check C libraries](https://github.com/hbgit/Map2Check/blob/master/modules/frontend/caller.cpp#L194-L279)
- [ ] [Generate ByteCode](https://github.com/hbgit/Map2Check/blob/master/modules/frontend/caller.cpp#L395-L403)

Also, some other fixes for caller (we should open an issue for Caller class only):
- [ ] [Stop using system and use Boost.Process](https://github.com/hbgit/Map2Check/blob/master/modules/frontend/caller.cpp#L327)
- [ ] [Check if we can use Klee API instead of calling binary](https://github.com/hbgit/Map2Check/blob/master/modules/frontend/caller.cpp#L288-L308)
- [ ] [Use Boost Regex library instead of 'sed' command](https://github.com/hbgit/Map2Check/blob/master/modules/frontend/caller.cpp#L381-L388)
- [ ] [Use Boost filesystem API](https://github.com/hbgit/Map2Check/blob/master/modules/frontend/caller.cpp#L410)
- [ ] [Check if we can use Crab API](https://github.com/hbgit/Map2Check/blob/master/modules/frontend/caller.cpp#L418)
